const Hospital = require('../models/Hospital');

const initialHospitals = [
  // TAMIL NADU - CHENNAI
  {
    name: 'Metro General Healthcare',
    code: 'MGH-01',
    state: 'Tamil Nadu',
    district: 'Chennai',
    area: 'Anna Nagar',
    address: '100 Medical Center Blvd, Anna Nagar',
    phone: '+91 44 2620 1234',
    rating: 4.8,
    emergencyServices: true,
    departments: ['Emergency Care', 'Cardiology', 'Pediatrics', 'Neurology', 'General Surgery'],
    currentQueueLength: 4,
    avgWaitTimeMinutes: 12,
    crowdStatus: 'Low',
    coordinates: { lat: 13.0827, lng: 80.2707 },
    operatingHours: '24/7 Emergency & Outpatient',
  },
  {
    name: 'Apollo Speciality Center',
    code: 'ASC-02',
    state: 'Tamil Nadu',
    district: 'Chennai',
    area: 'Adyar',
    address: '45 Lattice Bridge Road, Adyar',
    phone: '+91 44 2490 5678',
    rating: 4.9,
    emergencyServices: true,
    departments: ['Cardiology', 'Oncology', 'Orthopedics', 'ICU', 'Radiology'],
    currentQueueLength: 14,
    avgWaitTimeMinutes: 35,
    crowdStatus: 'High',
    coordinates: { lat: 13.0012, lng: 80.2565 },
    operatingHours: '24/7 Full Care Facility',
  },
  {
    name: 'Fortis Malar Hospital',
    code: 'FMH-03',
    state: 'Tamil Nadu',
    district: 'Chennai',
    area: 'T. Nagar',
    address: '12 Gandhi Road, T. Nagar',
    phone: '+91 44 2434 9000',
    rating: 4.7,
    emergencyServices: true,
    departments: ['Cardiology', 'Neurology', 'Gastroenterology', 'General Medicine'],
    currentQueueLength: 7,
    avgWaitTimeMinutes: 18,
    crowdStatus: 'Moderate',
    coordinates: { lat: 13.0418, lng: 80.2341 },
    operatingHours: '24/7 ER & Outpatient',
  },

  // TAMIL NADU - COIMBATORE
  {
    name: 'Kovai Medical Center & Hospital (KMCH)',
    code: 'KMC-04',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    area: 'Peelamedu',
    address: '999 Avinashi Road, Peelamedu',
    phone: '+91 422 432 3800',
    rating: 4.9,
    emergencyServices: true,
    departments: ['Trauma & Emergency', 'Cardiology', 'Pulmonology', 'Nephrology'],
    currentQueueLength: 9,
    avgWaitTimeMinutes: 22,
    crowdStatus: 'Moderate',
    coordinates: { lat: 11.0270, lng: 77.0266 },
    operatingHours: '24/7 Super Specialty',
  },
  {
    name: 'G. Kuppuswamy Naidu Memorial Hospital',
    code: 'GKN-05',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    area: 'RS Puram',
    address: 'P.N. Palayam Road, RS Puram',
    phone: '+91 422 224 5000',
    rating: 4.8,
    emergencyServices: true,
    departments: ['Pediatrics', 'Obstetrics & Gynecology', 'Oncology', 'General Surgery'],
    currentQueueLength: 5,
    avgWaitTimeMinutes: 15,
    crowdStatus: 'Low',
    coordinates: { lat: 11.0080, lng: 76.9530 },
    operatingHours: '24/7 Emergency Services',
  },
  {
    name: 'PSG Hospital & Research Institute',
    code: 'PSG-06',
    state: 'Tamil Nadu',
    district: 'Coimbatore',
    area: 'Gandhipuram',
    address: '100 Cross Cut Road, Gandhipuram',
    phone: '+91 422 257 0170',
    rating: 4.7,
    emergencyServices: true,
    departments: ['Dermatology', 'ENT', 'Ophthalmology', 'Orthopedics'],
    currentQueueLength: 8,
    avgWaitTimeMinutes: 20,
    crowdStatus: 'Moderate',
    coordinates: { lat: 11.0168, lng: 76.9658 },
    operatingHours: '24/7 ER & 8 AM - 8 PM OPD',
  },

  // TAMIL NADU - MADURAI
  {
    name: 'Meenakshi Mission Hospital & Research Centre',
    code: 'MMH-07',
    state: 'Tamil Nadu',
    district: 'Madurai',
    area: 'KK Nagar',
    address: 'Lake Area, KK Nagar',
    phone: '+91 452 258 8588',
    rating: 4.8,
    emergencyServices: true,
    departments: ['Emergency Care', 'Cardiology', 'Neurology', 'Urology'],
    currentQueueLength: 6,
    avgWaitTimeMinutes: 14,
    crowdStatus: 'Low',
    coordinates: { lat: 9.9252, lng: 78.1198 },
    operatingHours: '24/7 Full Care',
  },

  // MAHARASHTRA - MUMBAI
  {
    name: 'Lilavati Hospital & Research Centre',
    code: 'LIL-08',
    state: 'Maharashtra',
    district: 'Mumbai',
    area: 'Bandra East',
    address: 'A-791, Bandra Reclamation, Bandra East',
    phone: '+91 22 2675 1000',
    rating: 4.9,
    emergencyServices: true,
    departments: ['Cardiology', 'Neurosurgery', 'Orthopedics', 'Pediatrics'],
    currentQueueLength: 18,
    avgWaitTimeMinutes: 45,
    crowdStatus: 'Critical',
    coordinates: { lat: 19.0544, lng: 72.8285 },
    operatingHours: '24/7 Tertiary Care',
  },
  {
    name: 'Kokilaben Dhirubhai Ambani Hospital',
    code: 'KDA-09',
    state: 'Maharashtra',
    district: 'Mumbai',
    area: 'Andheri West',
    address: 'Rao Saheb Achutrao Patwardhan Marg, Andheri West',
    phone: '+91 22 4269 6969',
    rating: 4.9,
    emergencyServices: true,
    departments: ['Oncology', 'Cardiology', 'Robotic Surgery', 'Organ Transplant'],
    currentQueueLength: 12,
    avgWaitTimeMinutes: 30,
    crowdStatus: 'High',
    coordinates: { lat: 19.1314, lng: 72.8252 },
    operatingHours: '24/7 Full Care Facility',
  },
  {
    name: 'Hinduja National Hospital',
    code: 'HNH-10',
    state: 'Maharashtra',
    district: 'Mumbai',
    area: 'South Mumbai',
    address: 'Veer Savarkar Marg, Mahim',
    phone: '+91 22 2445 1515',
    rating: 4.7,
    emergencyServices: true,
    departments: ['General Medicine', 'Endocrinology', 'Pulmonology', 'ENT'],
    currentQueueLength: 8,
    avgWaitTimeMinutes: 20,
    crowdStatus: 'Moderate',
    coordinates: { lat: 19.0330, lng: 72.8397 },
    operatingHours: '24/7 ER & Outpatient',
  },

  // KARNATAKA - BENGALURU
  {
    name: 'Manipal Hospital HAL Airport Road',
    code: 'MPH-11',
    state: 'Karnataka',
    district: 'Bengaluru',
    area: 'Indiranagar',
    address: '98, HAL Airport Road, Indiranagar',
    phone: '+91 80 2502 4444',
    rating: 4.8,
    emergencyServices: true,
    departments: ['Cardiology', 'Neurology', 'Pediatrics', 'Trauma & Emergency'],
    currentQueueLength: 11,
    avgWaitTimeMinutes: 25,
    crowdStatus: 'Moderate',
    coordinates: { lat: 12.9582, lng: 77.6493 },
    operatingHours: '24/7 Multi-Specialty',
  },
  {
    name: 'Fortis Hospital Koramangala',
    code: 'FHK-12',
    state: 'Karnataka',
    district: 'Bengaluru',
    area: 'Koramangala',
    address: '154/9 Bannerghatta Road, Near Koramangala',
    phone: '+91 80 6621 4444',
    rating: 4.7,
    emergencyServices: true,
    departments: ['Orthopedics', 'Dermatology', 'Gastroenterology', 'Urology'],
    currentQueueLength: 5,
    avgWaitTimeMinutes: 12,
    crowdStatus: 'Low',
    coordinates: { lat: 12.9352, lng: 77.6245 },
    operatingHours: '24/7 Emergency & OPD',
  },

  // CALIFORNIA - LOS ANGELES
  {
    name: 'Cedars-Sinai Medical Center',
    code: 'CSM-13',
    state: 'California',
    district: 'Los Angeles',
    area: 'Beverly Hills',
    address: '8700 Beverly Blvd, Los Angeles',
    phone: '+1 (310) 423-3277',
    rating: 4.9,
    emergencyServices: true,
    departments: ['Emergency Care', 'Cardiology', 'Oncology', 'Neurosurgery'],
    currentQueueLength: 15,
    avgWaitTimeMinutes: 40,
    crowdStatus: 'High',
    coordinates: { lat: 34.0754, lng: -118.3802 },
    operatingHours: '24/7 Emergency Level 1 Trauma',
  },
  {
    name: 'UCLA Health Mattel Childrens Hospital',
    code: 'UCL-14',
    state: 'California',
    district: 'Los Angeles',
    area: 'Downtown',
    address: '757 Westwood Plaza, Los Angeles',
    phone: '+1 (310) 825-9111',
    rating: 4.8,
    emergencyServices: true,
    departments: ['Pediatrics', 'Neonatology', 'General Medicine', 'Child Neurology'],
    currentQueueLength: 3,
    avgWaitTimeMinutes: 10,
    crowdStatus: 'Low',
    coordinates: { lat: 34.0660, lng: -118.4452 },
    operatingHours: '24/7 Pediatric Emergency',
  },
];

const seedHospitals = async () => {
  try {
    const count = await Hospital.countDocuments();
    // Re-seed if empty or outdated schema
    if (count < 10) {
      await Hospital.deleteMany({});
      await Hospital.insertMany(initialHospitals);
      console.log(`[Seed Data] Successfully seeded ${initialHospitals.length} multi-state hospitals.`);
    } else {
      console.log(`[Seed Data] ${count} hospitals already exist in database.`);
    }
  } catch (error) {
    console.error('[Seed Data] Error seeding hospital records:', error.message);
  }
};

module.exports = seedHospitals;
